version: '3'

services:
  server:
    image: php:apache
    working_dir: /var/www/html
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: <something.nl/something.com>,<www.something.nl/www.something.com>,<etc>
      LETSENCRYPT_HOST: <something.nl/something.com>,<www.something.nl/www.something.com>,<etc>
    container_name: <something.nl/something.com>

networks:
  default:
    external:
      name: nginx-proxy
