version: '3'

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     expose:
       - 80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: PASSWORD
       WORDPRESS_DB_NAME: databasename
       VIRTUAL_HOST: <something.nl>,<www.something.nl>,<etc>
       LETSENCRYPT_HOST: <something.nl>,<www.something.nl>,<etc>
     volumes:
      - wordpress:/var/www/html
     container_name: <something.nl/something.com>
     
   db:
     image: mysql:5.7
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: PASSWORD
       MYSQL_DATABASE: databasename
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: PASSWORD
      volumes:
       - db:/var/lib/mysql
     container_name: <something.nl>_db
     
volumes:
    wordpress:
    db:

networks:
  default:
    external:
      name: nginx-proxy
      
