image: docker/compose:latest

stages:
  - deploy

deploy:
  stage: deploy
  tags: [ <TAG_NAME> ]
  script:
    - ls
    - docker container stop <something.nl/something.com> || true
    - docker container rm <something.nl/something.com> || true
    - docker-compose up -d
    - docker cp . <something.nl/something.com>:/var/www/html
    - docker ps -a
  only: [ master ]
